// data.js
const themes = {
    'Level 1：人物': [
{ en: "Adult", cn: "成人", pos: "n.", sen: "An adult needs to drive the car.", trans: "小孩應該由成人陪同。" },
{ en: "Angel", cn: "天使", pos: "n.", sen: "The little girl looks like an angel.", trans: "你看起來像個美麗的天使。" },
{ en: "Baby", cn: "嬰兒、寶貝", pos: "n.", sen: "The baby is sleeping now.", trans: "嬰兒正在床上睡覺。" },
{ en: "Boy", cn: "男孩", pos: "n.", sen: "That boy is my classmate.", trans: "那個男孩是我的弟弟。" },
{ en: "Child", cn: "小孩", pos: "n.", sen: "Every child likes to play games.", trans: "每個小孩都喜歡玩遊戲。" },
{ en: "Couple", cn: "情侶、夫妻", pos: "n.", sen: "They are a happy couple.", trans: "他們是一對非常幸福的夫妻。" },
{ en: "Customer", cn: "顧客", pos: "n.", sen: "The customer buys a toy in the shop.", trans: "顧客正在商店裡買食物。" },
{ en: "Fool", cn: "呆子", pos: "n.", sen: "Don't be a fool.", trans: "別當呆子，三思而後行。" },
{ en: "Genius", cn: "天才", pos: "n.", sen: "He is a genius at math.", trans: "愛因斯坦是一位偉大的天才。" },
{ en: "Gentleman", cn: "紳士", pos: "n.", sen: "My dad is a kind gentleman.", trans: "他是一位善良且有禮貌的紳士。" },
{ en: "Giant", cn: "巨人", pos: "n.", sen: "The giant is as tall as a house.", trans: "巨人住在一座大城堡裡。" },
{ en: "Girl", cn: "女孩", pos: "n.", sen: "The girl has long hair.", trans: "那個女孩穿著一件紅色的洋裝。" },
{ en: "Guest", cn: "客人、來賓", pos: "n.", sen: "We have a guest at home today.", trans: "我們有一位客人要來吃晚餐。" },
{ en: "Guy", cn: "傢伙", pos: "n.", sen: "He is a nice guy.", trans: "他是個不錯的傢伙。" },
{ en: "Hero", cn: "英雄", pos: "n.", sen: "Spider-Man is my hero.", trans: "消防員是我心目中的英雄。" },
{ en: "Host", cn: "男主(持)人", pos: "n.", sen: "The host says 'Welcome!'", trans: "男主人歡迎大家參加聚會。" },
{ en: "Kid", cn: "孩童、青年", pos: "n.", sen: "The kid is playing with a ball.", trans: "孩子，別傻了。" },
{ en: "King", cn: "國王", pos: "n.", sen: "The king lives in a big castle.", trans: "國王戴著金色的皇冠。" },
{ en: "Lady", cn: "淑女、女士", pos: "n.", sen: "She is a beautiful lady.", trans: "各位女士、先生，歡迎！" },
{ en: "Male", cn: "男性", pos: "n./adj.", sen: "My dog is a male.", trans: "這隻貓是公的還是母的？" },
{ en: "Man", cn: "男人", pos: "n.", sen: "The man is my father.", trans: "那個男人是一位醫生。" },
{ en: "Master", cn: "主人、大師", pos: "n.", sen: "He is the master of this house.", trans: "他是一位烹飪大師。" },
{ en: "Neighbor", cn: "鄰居", pos: "n.", sen: "My neighbor is very kind.", trans: "我的鄰居非常友善。" },
{ en: "Partner", cn: "夥伴", pos: "n.", sen: "You are my best partner.", trans: "她是我最好的舞伴。" },
{ en: "People", cn: "人們", pos: "n.", sen: "Many people are in the park.", trans: "公園裡有很多人。" },
{ en: "Person", cn: "人", pos: "n.", sen: "She is a good person.", trans: "她是一個非常善良的人。" },
{ en: "Prince", cn: "王子", pos: "n.", sen: "The prince rides a white horse.", trans: "王子住在城堡裡。" },
{ en: "Princess", cn: "公主", pos: "n.", sen: "The princess wears a pink dress.", trans: "公主非常漂亮。" },
{ en: "Queen", cn: "皇后", pos: "n.", sen: "The queen wears a gold crown.", trans: "皇后住在英國。" },
{ en: "Stranger", cn: "陌生人", pos: "n.", sen: "Do not talk to a stranger.", trans: "不要跟陌生人說話。" },
{ en: "Teenager", cn: "青少年", pos: "n.", sen: "My big brother is a teenager.", trans: "我弟弟是個 15 歲的青少年。" },
{ en: "Visitor", cn: "訪客", pos: "n.", sen: "The visitor looks at the map.", trans: "博物館裡有很多訪客。" },
{ en: "Woman", cn: "女人", pos: "n.", sen: "The woman is a teacher.", trans: "那位女人是我的母親。" },
{ en: "Youth", cn: "青年", pos: "n.", sen: "He is a healthy youth.", trans: "趁年輕時好好享受青春。" },
        // ... 其他單字
    ],
    'Level 2：外貌與個性': [{ en: "Heavy", cn: "重的", pos: "adj.", sen: "The box is too ____ for me to carry.", trans: "這個箱子太重了，我搬不動。" },
{ en: "Nice-looking", cn: "好看的", pos: "adj.", sen: "He is a ____ young man.", trans: "他是個長相好看的年輕人。" },
{ en: "Old", cn: "老的", pos: "adj.", sen: "My grandfather is very ____ but healthy.", trans: "我爺爺雖然年紀很大但很健康。" },
{ en: "Over-weight", cn: "超重的", pos: "adj.", sen: "Eating too much sugar makes you ____.", trans: "吃太多糖會讓你體重超重。" },
{ en: "Pretty", cn: "美麗、可愛的", pos: "adj.", sen: "She looks very ____ in that pink dress.", trans: "她穿那件粉色洋裝看起來非常漂亮。" },
{ en: "Short", cn: "短的、矮的", pos: "adj.", sen: "The pencil is too ____ to hold.", trans: "這枝鉛筆太短了，不好拿。" },
{ en: "Skinny", cn: "皮包骨的", pos: "adj.", sen: "The stray dog is very ____ and hungry.", trans: "那隻流浪狗瘦得皮包骨而且很餓。" },
{ en: "Slender", cn: "苗條、纖細的", pos: "adj.", sen: "The dancer has a ____ body.", trans: "那位舞者有著纖細的身材。" },
{ en: "Slim", cn: "苗條、纖細的", pos: "adj.", sen: "She stays ____ by exercising every day.", trans: "她靠每天運動來保持苗條。" },
{ en: "Tall", cn: "高的", pos: "adj.", sen: "My father is the ____est person in our family.", trans: "我爸爸是我們家最高的人。" },
{ en: "Thin", cn: "瘦的", pos: "adj.", sen: "He is tall and ____.", trans: "他長得又高又瘦。" },
{ en: "Under-weight", cn: "過輕的", pos: "adj.", sen: "The baby is a bit ____ for his age.", trans: "這個嬰兒的體重對他的年齡來說有點過輕。" },
{ en: "Ugly", cn: "醜的", pos: "adj.", sen: "There is no such thing as an ____ flower.", trans: "世上沒有醜陋的花朵。" },
{ en: "Young", cn: "年輕的", pos: "adj.", sen: "____ people enjoy listening to pop music.", trans: "年輕人喜歡聽流行音樂。" },
{ en: "Active", cn: "主動、積極的", pos: "adj.", sen: "He plays an ____ role in the classroom.", trans: "他在課堂上表現得很積極。" },
{ en: "Angry", cn: "生氣的", pos: "adj.", sen: "Please don't be ____ with me.", trans: "請不要生我的氣。" },
{ en: "Bad", cn: "壞的", pos: "adj.", sen: "Smoking is a ____ habit for your health.", trans: "吸菸是對健康有害的壞習慣。" },
{ en: "Bored", cn: "感到無聊的", pos: "adj.", sen: "I feel ____ when I have nothing to do.", trans: "沒事做的時候我會感到無聊。" },
{ en: "Boring", cn: "枯燥無趣的", pos: "adj.", sen: "The movie was so ____ that I fell asleep.", trans: "這部電影太無聊了，我看到睡著。" },
{ en: "Brave", cn: "勇敢的", pos: "adj.", sen: "The ____ boy saved the cat from the tree.", trans: "那個勇敢的男孩把貓從樹上救了下來。" },
{ en: "Busy", cn: "忙碌的", pos: "adj.", sen: "I am very ____ with my homework today.", trans: "我今天忙著寫功課。" },
{ en: "Careful", cn: "仔細、小心的", pos: "adj.", sen: "Be ____ when you cross the street.", trans: "過馬路時要小心。" },
{ en: "Careless", cn: "粗心的", pos: "adj.", sen: "He made a ____ mistake in the math test.", trans: "他在數學考試中犯了一個粗心的錯誤。" },
{ en: "Childish", cn: "幼稚的", pos: "adj.", sen: "Stop making ____ jokes in the meeting.", trans: "別在會議中開這種幼稚的玩笑了。" },
{ en: "Childlike", cn: "天真的", pos: "adj.", sen: "She has a ____ smile.", trans: "她擁有天真無邪的笑容。" },
{ en: "Clever", cn: "機敏、伶俐的", pos: "adj.", sen: "Monkeys are very ____ animals.", trans: "猴子是非常聰明的動物。" },
{ en: "Confident", cn: "有自信的", pos: "adj.", sen: "You should be ____ when you speak English.", trans: "你說英文時應該要有自信。" },
{ en: "Considerate", cn: "體貼的", pos: "adj.", sen: "It is ____ of you to help the old lady.", trans: "你能幫助那位老太太真是太體貼了。" },
{ en: "Cool", cn: "酷的", pos: "adj.", sen: "Wearing sunglasses makes him look ____.", trans: "戴墨鏡讓他看起來很酷。" },
{ en: "Crazy", cn: "瘋狂、狂熱的", pos: "adj.", sen: "My brother is ____ about soccer.", trans: "我哥哥對足球非常瘋狂。" },
{ en: "Cruel", cn: "冷酷的", pos: "adj.", sen: "It is ____ to hurt animals.", trans: "傷害動物是很殘忍的。" },
{ en: "Curious", cn: "好奇的", pos: "adj.", sen: "Children are ____ about everything.", trans: "小孩子對每件事都很好奇。" },
{ en: "Diligent", cn: "勤勉的", pos: "adj.", sen: "A ____ student always studies hard.", trans: "勤奮的學生總是努力讀書。" },
{ en: "Dishonest", cn: "不誠實的", pos: "adj.", sen: "Nobody likes a ____ person.", trans: "沒有人喜歡不誠實的人。" },
{ en: "Evil", cn: "邪惡的", pos: "adj.", sen: "The ____ witch lived in a dark cave.", trans: "邪惡的巫婆住在一個黑暗的洞穴裡。" },
{ en: "Energetic", cn: "有活力的", pos: "adj.", sen: "Children are always ____ and full of life.", trans: "孩子們總是充滿活力。" },
{ en: "Excited", cn: "感到興奮的", pos: "adj.", sen: "I am so ____ about the coming holiday.", trans: "我對即將到來的假期感到非常興奮。" },
{ en: "Exciting", cn: "刺激的", pos: "adj.", sen: "The roller coaster is very ____.", trans: "雲霄飛車非常刺激。" },
{ en: "Famous", cn: "有名的", pos: "adj.", sen: "He wants to be a ____ singer one day.", trans: "他希望有一天能成為著名的歌手。" },
{ en: "Foolish", cn: "愚蠢的", pos: "adj.", sen: "Don't be ____; listen to my advice.", trans: "別傻了，聽聽我的建議。" },
{ en: "Frank", cn: "坦白、直率的", pos: "adj.", sen: "To be ____, I don't really like the idea.", trans: "坦白說，我並不是很喜歡這個主意。" },
{ en: "Friendly", cn: "友善的", pos: "adj.", sen: "The people here are very ____.", trans: "這裡的人非常友善。" },
{ en: "Funny", cn: "好笑、古怪的", pos: "adj.", sen: "He told a ____ joke and we all laughed.", trans: "他講了一個好笑的笑話，我們都笑了。" },
{ en: "Gentle", cn: "溫和的", pos: "adj.", sen: "He is a ____ man with a kind heart.", trans: "他是一位心地善良、性格溫和的人。" },
{ en: "Generous", cn: "大方、慷慨的", pos: "adj.", sen: "It's ____ of you to share your lunch.", trans: "你願意分享你的午餐真是太大方了。" },
{ en: "Good", cn: "好的", pos: "adj.", sen: "Have a ____ time at the party!", trans: "在派對上玩得開心點！" },
{ en: "Greedy", cn: "貪心的", pos: "adj.", sen: "The ____ dog wanted all the bones.", trans: "那隻貪心的狗想要所有的骨頭。" },
{ en: "Happy", cn: "快樂的", pos: "adj.", sen: "I am so ____ to see you again.", trans: "很高興再次見到你。" },
{ en: "Hard-working", cn: "努力認真的", pos: "adj.", sen: "She is a ____ student and gets high marks.", trans: "她是個努力的學生，成績很好。" },
{ en: "Honest", cn: "誠實的", pos: "adj.", sen: "An ____ person does not tell lies.", trans: "誠實的人不說謊。" },
{ en: "Humble", cn: "謙虛的", pos: "adj.", sen: "Despite his success, he remains ____.", trans: "儘管他很成功，他依然保持謙虛。" },
{ en: "Humorous", cn: "幽默的", pos: "adj.", sen: "Our teacher is very ____ and tells jokes.", trans: "我們的老師很幽默，常講笑話。" },
{ en: "Interested", cn: "感到有興趣的", pos: "adj.", sen: "I am ____ in learning English.", trans: "我對學英文很有興趣。" },
{ en: "Jealous", cn: "忌妒的", pos: "adj.", sen: "Don't be ____ of your friend's success.", trans: "不要嫉妒朋友的成功。" },
{ en: "Kind", cn: "和藹、親切的", pos: "adj.", sen: "Thank you for being so ____ to me.", trans: "謝謝你對我這麼親切。" },
{ en: "Lazy", cn: "懶惰的", pos: "adj.", sen: "He is too ____ to clean his room.", trans: "他太懶了，不肯打掃房間。" },
{ en: "Lonely", cn: "孤獨、寂寞的", pos: "adj.", sen: "The old man feels ____ living alone.", trans: "那個老人獨自生活感到很寂寞。" },
{ en: "Lovely", cn: "可愛、美好的", pos: "adj.", sen: "What a ____ day for a walk!", trans: "多麼美好的一個散步日啊！" },
{ en: "Mad", cn: "發狂、惱火的", pos: "adj.", sen: "Mom was ____ because I broke the vase.", trans: "媽媽因為我打破花瓶而大發雷霆。" },
{ en: "Naughty", cn: "頑皮、淘氣的", pos: "adj.", sen: "The ____ boy hid his sister's toys.", trans: "那個淘氣的男孩把妹妹的玩具藏了起來。" },
{ en: "Nervous", cn: "緊張的", pos: "adj.", sen: "I always feel ____ before an exam.", trans: "考試前我總是感到緊張。" },
{ en: "Nice", cn: "美好、體面的", pos: "adj.", sen: "It's ____ to meet you.", trans: "很高興認識你。" },
{ en: "Patient", cn: "有耐心的", pos: "adj.", sen: "Teachers need to be ____ with students.", trans: "老師對學生需要有耐心。" },
{ en: "Polite", cn: "有禮貌的", pos: "adj.", sen: "It's ____ to say 'please'and 'thank you'.", trans: "說「請」和「謝謝」是有禮貌的表現。" },
{ en: "Poor", cn: "貧窮、可憐的", pos: "adj.", sen: "The ____ kitten was lost in the rain.", trans: "那隻可憐的小貓在雨中走丟了。" },
{ en: "Proud", cn: "驕傲、自豪的", pos: "adj.", sen: "My parents are ____ of my achievements.", trans: "我的父母為我的成就感到自豪。" },
{ en: "Rich", cn: "富有的", pos: "adj.", sen: "He became ____ by working very hard.", trans: "他透過努力工作變得富有。" },
{ en: "Rude", cn: "粗魯、無禮的", pos: "adj.", sen: "It is ____ to point at people.", trans: "對人指指點點是很粗魯的。" },
{ en: "Sad", cn: "傷心的", pos: "adj.", sen: "The movie was very ____ at the end.", trans: "這部電影的結尾非常傷心。" },
{ en: "Selfish", cn: "自私的", pos: "adj.", sen: "A ____ person only thinks about himself.", trans: "自私的人只想到自己。" },
{ en: "Shy", cn: "害羞的", pos: "adj.", sen: "The ____ girl hid behind her mother.", trans: "害羞的小女孩躲在媽媽後面。" },
{ en: "Silly", cn: "愚蠢、糊塗的", pos: "adj.", sen: "Don't make such a ____ mistake.", trans: "不要犯這種糊塗的錯誤。" },
{ en: "Sincere", cn: "真誠的", pos: "adj.", sen: "Please accept my ____ apology.", trans: "請接受我真誠的道歉。" },
{ en: "Smart", cn: "機警、瀟灑的", pos: "adj.", sen: "You look ____ in that new suit.", trans: "你穿那套新西裝看起來很瀟灑。" },
{ en: "Sneaky", cn: "鬼鬼祟祟的", pos: "adj.", sen: "The ____ cat stole a piece of fish.", trans: "那隻鬼鬼祟祟的貓偷了一塊魚。" },
{ en: "Stingy", cn: "小氣的", pos: "adj.", sen: "He is so ____ that he never buys gifts.", trans: "他太小氣了，從不買禮物。" },
{ en: "Stupid", cn: "笨的、遲鈍的", pos: "adj.", sen: "I feel ____ for forgetting your birthday.", trans: "我竟然忘了你的生日，我覺得自己好笨。" },
{ en: "Successful", cn: "成功的", pos: "adj.", sen: "She is a ____ businesswoman.", trans: "她是一位成功的女商人。" },
{ en: "Talkative", cn: "愛說話、健談的", pos: "adj.", sen: "My ____ roommate kept me up all night.", trans: "我那愛說話的室友讓我整晚沒睡。" },
{ en: "Unhappy", cn: "不快樂的", pos: "adj.", sen: "He was ____ with his test results.", trans: "他對自己的考試成績感到不快樂。" },
{ en: "Wise", cn: "有智慧的", pos: "adj.", sen: "It was a ____ choice to save your money.", trans: "把錢存起來是個明智的選擇。" },
{ en: "Beautiful", cn: "漂亮的", pos: "adj.", sen: "The princess is very ____.", trans: "公主非常漂亮。" },
{ en: "Blind", cn: "盲的", pos: "adj.", sen: "He helps ____ people with a guide dog.", trans: "他用導盲犬幫助盲人。" },
{ en: "Chubby", cn: "圓胖的", pos: "adj.", sen: "The baby has ____ red cheeks.", trans: "那個嬰兒有著圓胖的紅頰。" },
{ en: "Cute", cn: "可愛的", pos: "adj.", sen: "Look at that ____ little puppy!", trans: "看那隻可愛的小狗！" },
{ en: "Deaf", cn: "聾的", pos: "adj.", sen: "He uses sign language because he is ____.", trans: "因為他是聾子，所以使用手語。" },
{ en: "Dumb", cn: "啞的", pos: "adj.", sen: "The ____ boy expressed himself by drawing.", trans: "那個啞巴男孩透過畫畫來表達自己。" },
{ en: "Fat", cn: "胖的", pos: "adj.", sen: "The cat became ____ because it ate too much.", trans: "這隻貓因為吃太多變胖了。" },
{ en: "Beard", cn: "鬍子", pos: "n.", sen: "My father has a long black ____.", trans: "我父親留著長長的黑鬍子。" },

        // ... 其他單字
    ],
    'Level 3：身體部位與器官': [
        // ... 其他單字
    ],
    'Level 4：健康、症狀與醫療': [
        // ... 其他單字
    ],
    'Level 5：家庭成員與家庭': [
        // ... 其他單字
    ],
    'Level 6：稱呼': [
        // ... 其他單字
    ],
    'Level 7：數字': [
        // ... 其他單字
    ],
    
    // 依此類推到 Level 30
    'Level 30：進階主題': [
        // ... 其他單字
    ]
};
