// data.js
const themes = {
    'Level 1：人物': [
{ en: "Adult", cn: "成人", pos: "n.", sen: "An adult needs to drive the car.", trans: "小孩應該由成人陪同。" },
{ en: "Angel", cn: "天使", pos: "n.", sen: "The little girl looks like an angel.", trans: "你看起來像個美麗的天使。" },
{ en: "Baby", cn: "嬰兒、寶貝", pos: "n.", sen: "The baby is sleeping now.", trans: "嬰兒正在床上睡覺。" },
{ en: "Boy", cn: "男孩", pos: "n.", sen: "That boy is my classmate.", trans: "那個男孩是我的弟弟。" },
{ en: "Child", cn: "小孩", pos: "n.", sen: "Every child likes to play games.", trans: "每個小孩都喜歡玩遊戲。" },
{ en: "Couple", cn: "情侶、夫妻", pos: "n.", sen: "They are a happy couple.", trans: "他們是一對非常幸福的夫妻。" },
{ en: "Customer", cn: "顧客", pos: "n.", sen: "The customer buys a toy in the shop.", trans: "顧客正在商店裡買食物。" },
{ en: "Fool", cn: "呆子", pos: "n.", sen: "Don't be a fool.", trans: "別當呆子，三思而後行。" },
{ en: "Genius", cn: "天才", pos: "n.", sen: "He is a genius at math.", trans: "愛因斯坦是一位偉大的天才。" },
{ en: "Gentleman", cn: "紳士", pos: "n.", sen: "My dad is a kind gentleman.", trans: "他是一位善良且有禮貌的紳士。" },
{ en: "Giant", cn: "巨人", pos: "n.", sen: "The giant is as tall as a house.", trans: "巨人住在一座大城堡裡。" },
{ en: "Girl", cn: "女孩", pos: "n.", sen: "The girl has long hair.", trans: "那個女孩穿著一件紅色的洋裝。" },
{ en: "Guest", cn: "客人、來賓", pos: "n.", sen: "We have a guest at home today.", trans: "我們有一位客人要來吃晚餐。" },
{ en: "Guy", cn: "傢伙", pos: "n.", sen: "He is a nice guy.", trans: "他是個不錯的傢伙。" },
{ en: "Hero", cn: "英雄", pos: "n.", sen: "Spider-Man is my hero.", trans: "消防員是我心目中的英雄。" },
{ en: "Host", cn: "男主(持)人", pos: "n.", sen: "The host says 'Welcome!'", trans: "男主人歡迎大家參加聚會。" },
{ en: "Kid", cn: "孩童、青年", pos: "n.", sen: "The kid is playing with a ball.", trans: "孩子，別傻了。" },
{ en: "King", cn: "國王", pos: "n.", sen: "The king lives in a big castle.", trans: "國王戴著金色的皇冠。" },
{ en: "Lady", cn: "淑女、女士", pos: "n.", sen: "She is a beautiful lady.", trans: "各位女士、先生，歡迎！" },
{ en: "Male", cn: "男性", pos: "n./adj.", sen: "My dog is a male.", trans: "這隻貓是公的還是母的？" },
{ en: "Man", cn: "男人", pos: "n.", sen: "The man is my father.", trans: "那個男人是一位醫生。" },
{ en: "Master", cn: "主人、大師", pos: "n.", sen: "He is the master of this house.", trans: "他是一位烹飪大師。" },
{ en: "Neighbor", cn: "鄰居", pos: "n.", sen: "My neighbor is very kind.", trans: "我的鄰居非常友善。" },
{ en: "Partner", cn: "夥伴", pos: "n.", sen: "You are my best partner.", trans: "她是我最好的舞伴。" },
{ en: "People", cn: "人們", pos: "n.", sen: "Many people are in the park.", trans: "公園裡有很多人。" },
{ en: "Person", cn: "人", pos: "n.", sen: "She is a good person.", trans: "她是一個非常善良的人。" },
{ en: "Prince", cn: "王子", pos: "n.", sen: "The prince rides a white horse.", trans: "王子住在城堡裡。" },
{ en: "Princess", cn: "公主", pos: "n.", sen: "The princess wears a pink dress.", trans: "公主非常漂亮。" },
{ en: "Queen", cn: "皇后", pos: "n.", sen: "The queen wears a gold crown.", trans: "皇后住在英國。" },
{ en: "Stranger", cn: "陌生人", pos: "n.", sen: "Do not talk to a stranger.", trans: "不要跟陌生人說話。" },
{ en: "Teenager", cn: "青少年", pos: "n.", sen: "My big brother is a teenager.", trans: "我弟弟是個 15 歲的青少年。" },
{ en: "Visitor", cn: "訪客", pos: "n.", sen: "The visitor looks at the map.", trans: "博物館裡有很多訪客。" },
{ en: "Woman", cn: "女人", pos: "n.", sen: "The woman is a teacher.", trans: "那位女人是我的母親。" },
{ en: "Youth", cn: "青年", pos: "n.", sen: "He is a healthy youth.", trans: "趁年輕時好好享受青春。" },
        // ... 其他單字
    ],
    'Level 2：外貌與個性': [{ en: "Heavy", cn: "重的", pos: "adj.", sen: "This big box is very heavy.", trans: "這個大箱子非常重。" },
{ en: "Nice-looking", cn: "好看的", pos: "adj.", sen: "He is a nice-looking boy.", trans: "他是一個長得好看的男孩。" },
{ en: "Old", cn: "老的", pos: "adj.", sen: "My grandfather is very old.", trans: "我的祖父年紀很大了。" },
{ en: "Over-weight", cn: "超重的", pos: "adj.", sen: "You are over-weight and need to exercise.", trans: "你體重超重了，需要運動。" },
{ en: "Pretty", cn: "美麗、可愛的", pos: "adj.", sen: "The flowers in the garden are pretty.", trans: "花園裡的花很漂亮。" },
{ en: "Short", cn: "短的、矮的", pos: "adj.", sen: "The pencil is very short.", trans: "這枝鉛筆很短。" },
{ en: "Skinny", cn: "皮包骨的", pos: "adj.", sen: "The dog is skinny because it is hungry.", trans: "那隻狗因為很餓所以皮包骨。" },
{ en: "Slender", cn: "苗條、纖細的", pos: "adj.", sen: "The dancer has a slender body.", trans: "那位舞者有苗條的身材。" },
{ en: "Slim", cn: "苗條、纖細的", pos: "adj.", sen: "My sister is slim and tall.", trans: "我姊姊又苗條又高。" },
{ en: "Tall", cn: "高的", pos: "adj.", sen: "My brother is very tall.", trans: "我哥哥很高。" },
{ en: "Thin", cn: "瘦的", pos: "adj.", sen: "He is thin but very strong.", trans: "他很瘦但是很強壯。" },
{ en: "Under-weight", cn: "過輕的", pos: "adj.", sen: "The baby is small and under-weight.", trans: "這個寶寶很小且體重過輕。" },
{ en: "Ugly", cn: "醜的", pos: "adj.", sen: "The monster in the story is ugly.", trans: "故事裡的怪物很醜。" },
{ en: "Young", cn: "年輕的", pos: "adj.", sen: "The young teacher is very kind.", trans: "那位年輕老師非常親切。" },
{ en: "Active", cn: "主動、積極的", pos: "adj.", sen: "He is an active student in class.", trans: "他在班上是個積極的小孩。" },
{ en: "Angry", cn: "生氣的", pos: "adj.", sen: "Dad is angry because I broke the vase.", trans: "爸爸很生氣，因為我打破了花瓶。" },
{ en: "Bad", cn: "壞的", pos: "adj.", sen: "Do not be a bad boy.", trans: "不要當一個壞孩子。" },
{ en: "Bored", cn: "感到無聊的", pos: "adj.", sen: "I feel bored on a rainy day.", trans: "下雨天我覺得很無聊。" },
{ en: "Boring", cn: "枯燥無趣的", pos: "adj.", sen: "This movie is very boring.", trans: "這部電影非常枯燥。" },
{ en: "Brave", cn: "勇敢的", pos: "adj.", sen: "The brave fireman saved the cat.", trans: "勇敢的消防員救了那隻貓。" },
{ en: "Busy", cn: "忙碌的", pos: "adj.", sen: "Mom is busy in the kitchen.", trans: "媽媽正在廚房忙碌。" },
{ en: "Careful", cn: "仔細、小心的", pos: "adj.", sen: "Please be careful with the glass.", trans: "請小心拿這個玻璃杯。" },
{ en: "Careless", cn: "粗心的", pos: "adj.", sen: "He is careless and lost his pen.", trans: "他很粗心，弄丟了筆。" },
{ en: "Childish", cn: "幼稚的", pos: "adj.", sen: "His joke is a bit childish.", trans: "他的笑話有點幼稚。" },
{ en: "Childlike", cn: "天真的", pos: "adj.", sen: "She has a childlike smile.", trans: "她擁有天真無邪的笑容。" },
{ en: "Clever", cn: "機敏、伶俐的", pos: "adj.", sen: "The clever dog can open the door.", trans: "那隻聰明的狗會開門。" },
{ en: "Confident", cn: "有自信的", pos: "adj.", sen: "I am confident about the test.", trans: "我對這次考試很有信心。" },
{ en: "Considerate", cn: "體體貼的", pos: "adj.", sen: "It is considerate of you to help me.", trans: "你能幫我真是太體貼了。" },
{ en: "Cool", cn: "酷的", pos: "adj.", sen: "Your new bicycle is very cool.", trans: "你的新腳踏車非常酷。" },
{ en: "Crazy", cn: "瘋狂、狂熱的", pos: "adj.", sen: "He is crazy about soccer.", trans: "他對足球非常狂熱。" },
{ en: "Cruel", cn: "冷酷的", pos: "adj.", sen: "The cruel king was not happy.", trans: "那位冷酷的國王並不快樂。" },
{ en: "Curious", cn: "好奇的", pos: "adj.", sen: "The curious cat is looking at the fish.", trans: "好奇的貓正在看著魚。" },
{ en: "Diligent", cn: "勤勉的", pos: "adj.", sen: "She is a diligent student.", trans: "她是一位勤勉的學生。" },
{ en: "Dishonest", cn: "不誠實的", pos: "adj.", sen: "It is wrong to be dishonest.", trans: "不誠實是不對的。" },
{ en: "Evil", cn: "邪惡的", pos: "adj.", sen: "The evil witch has a black cat.", trans: "邪惡的巫婆有一隻黑貓。" },
{ en: "Energetic", cn: "有活力的", pos: "adj.", sen: "The kids are very energetic.", trans: "孩子們非常有活力。" },
{ en: "Excited", cn: "感到興奮的", pos: "adj.", sen: "I am excited about the trip.", trans: "我對這次旅行感到很興奮。" },
{ en: "Exciting", cn: "刺激的", pos: "adj.", sen: "The basketball game is exciting.", trans: "那場籃球比賽很刺激。" },
{ en: "Famous", cn: "有名的", pos: "adj.", sen: "He is a famous singer.", trans: "他是一位著名的歌手。" },
{ en: "Foolish", cn: "愚蠢的", pos: "adj.", sen: "It is foolish to run in the rain.", trans: "在雨中跑步是很愚蠢的。" },
{ en: "Frank", cn: "坦白、直率的", pos: "adj.", sen: "To be frank, I don't like the soup.", trans: "老實說，我不喜歡這碗湯。" },
{ en: "Friendly", cn: "友善的", pos: "adj.", sen: "Our neighbors are very friendly.", trans: "我們的鄰居非常友善。" },
{ en: "Funny", cn: "好笑、古怪的", pos: "adj.", sen: "The clown is very funny.", trans: "那個小丑非常搞笑。" },
{ en: "Gentle", cn: "溫和的", pos: "adj.", sen: "He has a gentle voice.", trans: "他的聲音很溫和。" },
{ en: "Generous", cn: "大方、慷慨的", pos: "adj.", sen: "My uncle is generous to us.", trans: "我叔叔對我們很大方。" },
{ en: "Good", cn: "好的", pos: "adj.", sen: "You are a good friend.", trans: "你是一個好朋友。" },
{ en: "Greedy", cn: "貪心的", pos: "adj.", sen: "Don't be greedy with the candy.", trans: "不要對糖果太貪心。" },
{ en: "Happy", cn: "快樂的", pos: "adj.", sen: "Today is a happy day.", trans: "今天是快樂的一天。" },
{ en: "Hard-working", cn: "努力認真的", pos: "adj.", sen: "The hard-working ant collects food.", trans: "努力的螞蟻在收集食物。" },
{ en: "Honest", cn: "誠實的", pos: "adj.", sen: "An honest boy does not tell lies.", trans: "誠實的孩子不撒謊。" },
{ en: "Humble", cn: "謙虛的", pos: "adj.", sen: "The wise man is very humble.", trans: "那位智者非常謙虛。" },
{ en: "Humorous", cn: "幽默的", pos: "adj.", sen: "My teacher is very humorous.", trans: "我的老師非常幽默。" },
{ en: "Interested", cn: "感到有興趣的", pos: "adj.", sen: "I am interested in music.", trans: "我對音樂感興趣。" },
{ en: "Jealous", cn: "忌妒的", pos: "adj.", sen: "Don't be jealous of his new toy.", trans: "不要嫉妒他的新玩具。" },
{ en: "Kind", cn: "和藹、親切的", pos: "adj.", sen: "The kind lady gave me a cookie.", trans: "那位親切的女士給了我一塊餅乾。" },
{ en: "Lazy", cn: "懶惰的", pos: "adj.", sen: "Get up! Don't be lazy.", trans: "快起床！不要懶惰。" },
{ en: "Lonely", cn: "孤獨、寂寞的", pos: "adj.", sen: "I feel lonely without my friends.", trans: "沒有朋友我覺得很寂寞。" },
{ en: "Lovely", cn: "可愛、美好的", pos: "adj.", sen: "What a lovely day!", trans: "多麼美好的一天啊！" },
{ en: "Mad", cn: "發狂、惱火的", pos: "adj.", sen: "Mom is mad at the messy room.", trans: "媽媽對凌亂的房間感到很惱火。" },
{ en: "Naughty", cn: "頑皮、淘氣的", pos: "adj.", sen: "The naughty boy hid my shoes.", trans: "那個頑皮的小男孩藏了我的鞋子。" },
{ en: "Nervous", cn: "緊張的", pos: "adj.", sen: "I am nervous about the show.", trans: "我對表演感到很緊張。" },
{ en: "Nice", cn: "美好、體面的", pos: "adj.", sen: "It is a nice house.", trans: "這是一間很棒的房子。" },
{ en: "Patient", cn: "有耐心的", pos: "adj.", sen: "You must be patient with the cat.", trans: "你對這隻貓必須有耐心。" },
{ en: "Polite", cn: "有禮貌的", pos: "adj.", sen: "A polite student says 'Thank you'.", trans: "有禮貌的學生會說「謝謝」。" },
{ en: "Poor", cn: "貧窮、可憐的", pos: "adj.", sen: "The poor bird cannot fly.", trans: "這隻可憐的鳥不會飛。" },
{ en: "Proud", cn: "驕傲、自豪的", pos: "adj.", sen: "I am proud of my father.", trans: "我以我父親為榮。" },
{ en: "Rich", cn: "富有的", pos: "adj.", sen: "The rich man has many cars.", trans: "那個富人有很多車。" },
{ en: "Rude", cn: "粗魯、無禮的", pos: "adj.", sen: "It is rude to shout in the library.", trans: "在圖書館大叫是很無禮的。" },
{ en: "Sad", cn: "傷心的", pos: "adj.", sen: "I am sad because my dog is lost.", trans: "我很傷心因為我的狗丟了。" },
{ en: "Selfish", cn: "自私的", pos: "adj.", sen: "Don't be selfish; share your toys.", trans: "不要自私，要分享你的玩具。" },
{ en: "Shy", cn: "害羞的", pos: "adj.", sen: "The shy girl hid behind her mom.", trans: "那個害羞的女孩躲在媽媽後面。" },
{ en: "Silly", cn: "愚蠢、糊塗的", pos: "adj.", sen: "He made a silly mistake.", trans: "他犯了一個糊塗的錯誤。" },
{ en: "Sincere", cn: "真誠的", pos: "adj.", sen: "She gave me a sincere apology.", trans: "她給了我一個真誠的道歉。" },
{ en: "Smart", cn: "機警、瀟灑的", pos: "adj.", sen: "You look smart in that suit.", trans: "你穿那套西裝看起來很帥氣（機警）。" },
{ en: "Sneaky", cn: "鬼鬼祟祟的", pos: "adj.", sen: "The sneaky cat stole the fish.", trans: "那隻鬼鬼祟祟的貓偷走了魚。" },
{ en: "Stingy", cn: "小氣的", pos: "adj.", sen: "He is stingy and never buys gifts.", trans: "他很小氣，從不買禮物。" },
{ en: "Stupid", cn: "笨的、遲鈍的", pos: "adj.", sen: "I feel stupid for forgetting my bag.", trans: "我覺得自己忘記帶包包很笨。" },
{ en: "Successful", cn: "成功的", pos: "adj.", sen: "He is a successful businessman.", trans: "他是一位成功的商人。" },
{ en: "Talkative", cn: "愛說話、健談的", pos: "adj.", sen: "My friend is very talkative.", trans: "我的朋友非常愛說話。" },
{ en: "Unhappy", cn: "不快樂的", pos: "adj.", sen: "She looks unhappy today.", trans: "她今天看起來不快樂。" },
{ en: "Wise", cn: "有智慧的", pos: "adj.", sen: "The old king was very wise.", trans: "那位老國王非常有智慧。" },
{ en: "Beautiful", cn: "漂亮的", pos: "adj.", sen: "The butterfly is so beautiful.", trans: "這隻蝴蝶真漂亮。" },
{ en: "Blind", cn: "盲的", pos: "adj.", sen: "The blind man uses a stick.", trans: "那位盲人使用手杖。" },
{ en: "Chubby", cn: "圓胖的", pos: "adj.", sen: "The baby has chubby cheeks.", trans: "那個寶寶有圓圓胖胖的臉頰。" },
{ en: "Cute", cn: "可愛的", pos: "adj.", sen: "That rabbit is very cute.", trans: "那隻兔子非常可愛。" },
{ en: "Deaf", cn: "聾的", pos: "adj.", sen: "He uses signs because he is deaf.", trans: "因為他聾了，所以使用手語。" },
{ en: "Dumb", cn: "啞的", pos: "adj.", sen: "A dumb person cannot speak.", trans: "啞巴不能說話。" },
{ en: "Fat", cn: "胖的", pos: "adj.", sen: "The cat is too fat to run.", trans: "這隻貓太胖了跑不動。" },
        // ... 其他單字
    ],
    'Level 3：身體部位與器官': [{ en: "Chin", cn: "下巴", pos: "n.", sen: "He touched his ____ while thinking.", trans: "他思考時摸著自己的下巴。" },
{ en: "Ear", cn: "耳朵", pos: "n.", sen: "We use our ____s to listen to music.", trans: "我們用耳朵聽音樂。" },
{ en: "Eye", cn: "眼睛", pos: "n.", sen: "She has big blue ____s.", trans: "她有一雙藍色的大眼睛。" },
{ en: "Face", cn: "臉", pos: "n.", sen: "Wash your ____ before going to bed.", trans: "睡覺前要洗臉。" },
{ en: "Hair", cn: "頭發", pos: "n.", sen: "She has long curly ____.", trans: "她有一頭長長的捲髮。" },
{ en: "Lip", cn: "嘴唇", pos: "n.", sen: "She put some balm on her dry ____s.", trans: "她在乾裂的嘴唇上塗了些護唇膏。" },
{ en: "Mouth", cn: "嘴巴", pos: "n.", sen: `Open your Mouth and say Ah.`, trans: `張開嘴巴說「啊」。` },
{ en: "Nose", cn: "鼻子", pos: "n.", sen: "The dog has a very good ____.", trans: "這隻狗的嗅覺（鼻子）非常靈敏。" },
{ en: "Tongue", cn: "舌頭", pos: "n.", sen: "Don't stick your ____ out at people.", trans: "不要對人吐舌頭。" },
{ en: "Tooth", cn: "牙齒", pos: "n.", sen: "I brush my ____s every morning.", trans: "我每天早上刷牙。" },
{ en: "Ankle", cn: "腳踝", pos: "n.", sen: "I hurt my ____ playing basketball.", trans: "我打籃球時扭傷了腳踝。" },
{ en: "Arm", cn: "手臂", pos: "n.", sen: "He broke his left ____ in the accident.", trans: "他在事故中摔斷了左手。" },
{ en: "Back", cn: "背部", pos: "n.", sen: "My ____ hurts from sitting too long.", trans: "坐太久讓我的背很痛。" },
{ en: "Body", cn: "身體", pos: "n.", sen: "Exercise is good for your ____.", trans: "運動對你的身體有益。" },
{ en: "Bone", cn: "骨頭", pos: "n.", sen: "The dog is chewing a ____.", trans: "狗正在啃骨頭。" },
{ en: "Finger", cn: "手指", pos: "n.", sen: "I have ten ____s on my hands.", trans: "我的雙手共有十根手指。" },
{ en: "Foot", cn: "腳", pos: "n.", sen: "My ____s are tired from walking.", trans: "走路走得我的腳很累。" },
{ en: "Hand", cn: "手", pos: "n.", sen: "Please wash your ____s before dinner.", trans: "晚餐前請洗手。" },
{ en: "Head", cn: "頭", pos: "n.", sen: "Wear a hat to protect your ____.", trans: "戴帽子來保護你的頭。" },
{ en: "Hip", cn: "臀部", pos: "n.", sen: "She put her hands on her ____s.", trans: "她把雙手放在臀部上（叉腰）。" },
{ en: "Knee", cn: "膝蓋", pos: "n.", sen: "He fell and hurt his ____.", trans: "他跌倒傷到了膝蓋。" },
{ en: "Leg", cn: "腿", pos: "n.", sen: "A table has four ____s.", trans: "桌子有四條腿。" },
{ en: "Nail", cn: "指甲", pos: "n.", sen: "Don't bite your ____s.", trans: "不要咬指甲。" },
{ en: "Neck", cn: "脖子", pos: "n.", sen: "She wore a scarf around her ____.", trans: "她在脖子上圍了一條圍巾。" },
{ en: "Shoulder", cn: "肩膀", pos: "n.", sen: "He carried the bag on his ____.", trans: "他把袋子扛在肩膀上。" },
{ en: "Skin", cn: "皮膚", pos: "n.", sen: "Use sunscreen to protect your ____.", trans: "用防曬乳來保護你的皮膚。" },
{ en: "Throat", cn: "喉嚨", pos: "n.", sen: "I have a sore ____ and cannot speak.", trans: "我喉嚨痛，沒法說話。" },
{ en: "Thumb", cn: "拇指", pos: "n.", sen: "He gave me a ____s-up.", trans: "他對我豎起了大拇指。" },
{ en: "Toe", cn: "腳趾", pos: "n.", sen: "I stubbed my ____ against the table.", trans: "我的腳趾撞到了桌子。" },
{ en: "Waist", cn: "腰", pos: "n.", sen: "This belt is too small for my ____.", trans: "這條皮帶對我的腰來說太小了。" },
{ en: "Wrist", cn: "手腕", pos: "n.", sen: "He wears a watch on his left ____.", trans: "他在左手腕上戴著手錶。" },
{ en: "Heart", cn: "心(臟)", pos: "n.", sen: "Your ____ beats faster when you run.", trans: "跑步時你的心跳會加快。" },
{ en: "Stomach", cn: "胃", pos: "n.", sen: "Don't exercise on a full ____.", trans: "飽腹（胃很滿）時不要運動。" },
{ en: "Comfortable", cn: "舒適的", pos: "adj.", sen: "This sofa is very ____.", trans: "這張沙發非常舒適。" },

        // ... 其他單字
    ],
    'Level 4：健康、症狀與醫療': [
        // ... 其他單字
    ],
    'Level 5：家庭成員與家庭': [
        // ... 其他單字
    ],
    'Level 6：稱呼': [
        // ... 其他單字
    ],
    'Level 7：數字': [
        // ... 其他單字
    ],
    
    // 依此類推到 Level 30
    'Level 30：進階主題': [
        // ... 其他單字
    ]
};
